FROM nginx

RUN apt update && \
    apt install -y \
    gcc \
    spawn-fcgi \
    libfcgi-dev && \
    rm -rf /var/lib/apt/lists

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./server/server.c /home/server.c
COPY ./start2.sh /home/start.sh

RUN chown -R nginx:nginx /home && chmod -R 755 /home && \
        chown -R nginx:nginx /var/cache/nginx && \
        chown -R nginx:nginx /var/log/nginx && \
        chown -R nginx:nginx /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && \
        chown -R nginx:nginx /var/run/nginx.pid

RUN chmod u-s /usr/bin/newgrp; \
    chmod u-s /bin/su; \
	chmod g-s /usr/bin/wall; \
	chmod u-s /usr/bin/chsh; \
	chmod u-s /usr/bin/chfn; \
	chmod u-s /bin/umount; \
	chmod g-s /sbin/unix_chkpwd; \
	chmod u-s /usr/bin/gpasswd; \
	chmod g-s /usr/bin/chage; \
	chmod u-s /usr/bin/passwd; \
	chmod g-s /usr/bin/expiry; \
	chmod u-s /bin/mount;

USER nginx
WORKDIR /home/

HEALTHCHECK CMD curl --fail localhost:81 || exit 1
ENTRYPOINT ["sh", "./start.sh"]